pipeline:
  identifier: Build_tadashi0713_demo_react_app_1776311028227
  name: Build demo-react-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1776310936817
        repoName: tadashi0713/demo-react-app
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: install nodejs
                  identifier: install_nodejs
                  spec:
                    shell: Bash
                    command: |-
                      mkdir $HOME/nodejs
                      curl -L https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz | tar xJ -C $HOME/nodejs
                      export PATH=$HOME/nodejs/node-v${NODE_VERSION}-linux-x64/bin:$PATH
                    envVariables:
                      NODE_VERSION: "20.12"
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    shell: Bash
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    shell: Bash
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    shell: Bash
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>
                    repo: tadashi0713/demo-react-app
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: node:25-alpine
                connectorRef: account.dockerhub
        type: CI
    - stage:
        name: Docker
        identifier: Docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.dockerhub
                    repo: tadashi0713/demo-react-app
                    tags:
                      - latest
