pipeline:
  identifier: Build_tadashi0713_demo_react_app_1776311028227
  name: Build demo-react-app
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1776310936817
        repoName: tadashi0713/demo-react-app
  stages:
    - stage:
        name: build
        identifier: build1
        template:
          templateRef: Nodejs_CI_Template
          versionLabel: "1"
